[theme]
primaryColor = "#4ADE80"               # Vibrant green (used for buttons and highlights)
backgroundColor = "#1E1E2F"            # Very dark blue-gray background
secondaryBackgroundColor = "#2C2C3E"   # Dark purple-gray for cards and sidebars
textColor = "#F8FAFC"                  # Soft white for readability
font = "sans serif"
